# Generated by Django 5.0.1 on 2024-03-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0003_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo_de_animal', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10)),
                ('disponibilidad', models.BooleanField()),
            ],
        ),
    ]
