# Generated by Django 5.0.1 on 2024-03-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0004_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='tipo_de_animal',
        ),
    ]
