# Generated by Django 5.0.1 on 2024-03-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0006_remove_medicamento_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicamento',
            new_name='Medicina',
        ),
        migrations.RenameField(
            model_name='medicina',
            old_name='nombre_medicamento',
            new_name='nombre_medicina',
        ),
    ]
