# Generated by Django 5.0.1 on 2024-03-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0007_rename_medicamento_medicina_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicina',
            new_name='Medicamento',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='nombre_medicina',
            new_name='nombre_medicamento',
        ),
    ]
