# Generated by Django 5.0.1 on 2024-03-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0008_rename_medicina_medicamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
