# Generated by Django 5.0.1 on 2024-03-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0009_medicamento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='tipo_de_animal',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], default='perro', max_length=5),
        ),
    ]
