# Generated by Django 5.0.1 on 2024-03-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0011_alter_medicamento_tipo_de_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mascota',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_de_animal',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=20),
        ),
    ]
