# Generated by Django 5.0.1 on 2024-03-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0012_alter_cliente_mascota_alter_mascota_tipo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
