# Generated by Django 5.0.1 on 2024-03-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mascota', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=20)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_ult_compra', models.DateField()),
            ],
        ),
    ]
